/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeacherRegisterRouteImport } from './routes/teacher-register'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherApprovalsRouteImport } from './routes/teacher.approvals'
import { Route as ParentRegisterRouteImport } from './routes/parent.register'
import { Route as ParentNotificationsRouteImport } from './routes/parent.notifications'
import { Route as ParentDownloadsRouteImport } from './routes/parent.downloads'
import { Route as ParentApplicationsRouteImport } from './routes/parent.applications'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminCardTemplatesRouteImport } from './routes/admin.card-templates'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRegisterRoute = TeacherRegisterRouteImport.update({
  id: '/teacher-register',
  path: '/teacher-register',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherApprovalsRoute = TeacherApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => TeacherRoute,
} as any)
const ParentRegisterRoute = ParentRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ParentRoute,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDownloadsRoute = ParentDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => ParentRoute,
} as any)
const ParentApplicationsRoute = ParentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ParentRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardTemplatesRoute = AdminCardTemplatesRouteImport.update({
  id: '/card-templates',
  path: '/card-templates',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-register': typeof TeacherRegisterRoute
  '/templates': typeof TemplatesRoute
  '/admin/card-templates': typeof AdminCardTemplatesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/parent/applications': typeof ParentApplicationsRoute
  '/parent/downloads': typeof ParentDownloadsRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/register': typeof ParentRegisterRoute
  '/teacher/approvals': typeof TeacherApprovalsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-register': typeof TeacherRegisterRoute
  '/templates': typeof TemplatesRoute
  '/admin/card-templates': typeof AdminCardTemplatesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/parent/applications': typeof ParentApplicationsRoute
  '/parent/downloads': typeof ParentDownloadsRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/register': typeof ParentRegisterRoute
  '/teacher/approvals': typeof TeacherApprovalsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-register': typeof TeacherRegisterRoute
  '/templates': typeof TemplatesRoute
  '/admin/card-templates': typeof AdminCardTemplatesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/parent/applications': typeof ParentApplicationsRoute
  '/parent/downloads': typeof ParentDownloadsRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/register': typeof ParentRegisterRoute
  '/teacher/approvals': typeof TeacherApprovalsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/features'
    | '/login'
    | '/parent'
    | '/teacher'
    | '/teacher-register'
    | '/templates'
    | '/admin/card-templates'
    | '/admin/reports'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/parent/applications'
    | '/parent/downloads'
    | '/parent/notifications'
    | '/parent/register'
    | '/teacher/approvals'
    | '/teacher/reports'
    | '/teacher/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/features'
    | '/login'
    | '/parent'
    | '/teacher'
    | '/teacher-register'
    | '/templates'
    | '/admin/card-templates'
    | '/admin/reports'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/parent/applications'
    | '/parent/downloads'
    | '/parent/notifications'
    | '/parent/register'
    | '/teacher/approvals'
    | '/teacher/reports'
    | '/teacher/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/features'
    | '/login'
    | '/parent'
    | '/teacher'
    | '/teacher-register'
    | '/templates'
    | '/admin/card-templates'
    | '/admin/reports'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/parent/applications'
    | '/parent/downloads'
    | '/parent/notifications'
    | '/parent/register'
    | '/teacher/approvals'
    | '/teacher/reports'
    | '/teacher/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TeacherRegisterRoute: typeof TeacherRegisterRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-register': {
      id: '/teacher-register'
      path: '/teacher-register'
      fullPath: '/teacher-register'
      preLoaderRoute: typeof TeacherRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/approvals': {
      id: '/teacher/approvals'
      path: '/approvals'
      fullPath: '/teacher/approvals'
      preLoaderRoute: typeof TeacherApprovalsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/parent/register': {
      id: '/parent/register'
      path: '/register'
      fullPath: '/parent/register'
      preLoaderRoute: typeof ParentRegisterRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/downloads': {
      id: '/parent/downloads'
      path: '/downloads'
      fullPath: '/parent/downloads'
      preLoaderRoute: typeof ParentDownloadsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/applications': {
      id: '/parent/applications'
      path: '/applications'
      fullPath: '/parent/applications'
      preLoaderRoute: typeof ParentApplicationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/card-templates': {
      id: '/admin/card-templates'
      path: '/card-templates'
      fullPath: '/admin/card-templates'
      preLoaderRoute: typeof AdminCardTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCardTemplatesRoute: typeof AdminCardTemplatesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSchoolsRoute: typeof AdminSchoolsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCardTemplatesRoute: AdminCardTemplatesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSchoolsRoute: AdminSchoolsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentRouteChildren {
  ParentApplicationsRoute: typeof ParentApplicationsRoute
  ParentDownloadsRoute: typeof ParentDownloadsRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentRegisterRoute: typeof ParentRegisterRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentApplicationsRoute: ParentApplicationsRoute,
  ParentDownloadsRoute: ParentDownloadsRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentRegisterRoute: ParentRegisterRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface TeacherRouteChildren {
  TeacherApprovalsRoute: typeof TeacherApprovalsRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherApprovalsRoute: TeacherApprovalsRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TeacherRegisterRoute: TeacherRegisterRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
